POST http://localhost:8080/films
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsQHRlc3QuY29tIiwiZXhwIjoxNzEwOTUxODg2LCJ1c2VySWQiOiIxMjMtYWJjLXF3ZXJ0eSJ9.nPCd1BFEsvVQJCMxeEvMdt5rXgTZjeVQnieQScJehx8

{
  "id": "123-abc-qwerty",
  "name": "Film name",
  "type": "Movie",
  "description": "Film description will go here for the film.",
  "categories": [
    "Action", 
    "Thriller", 
    "Horror"
  ],
	"likes": 15,
	"dislikes": 2,
	"comments": [
    "This is a great film",
    "Could do with more action"
  ]
}
