POST http://localhost:8080/films
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsQHRlc3QuY29tIiwiZXhwIjoxNzExMjk0MjM0LCJ1c2VySWQiOiJjMGE0Y2ZiOS0yMzcxLTRiYzEtYTg3Ny1mY2I1NzNhYWNkOTAifQ.fku7nIYd5IAkONycSpei_ZNJsQnb6dqyaqA0pmz8B4M

{
  "name": "Film name",
  "type": "Movie",
  "description": "Film description will go here for the film.",
  "categories": [
    "Action", 
    "Thriller", 
    "Horror"
  ],
	"likes": 15,
	"dislikes": 2,
	"comments": [
    "This is a great film",
    "Could do with more action"
  ],
  "locked": true
}
