DELETE http://localhost:8080/films/123-abc-qwerty
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsMUB0ZXN0LmNvbSIsImV4cCI6MTcxMTAzMDAxNCwidXNlcklkIjoiNzg5LWFiYy1xd2VydHkifQ.KxzgKtkAAhlF57UW0uMUjTtXTbE2Gsb7BgvGL0XAido

{
  "id": "123-abc-qwerty"
}
