PUT http://localhost:8080/films/like/58c771a7-4621-47af-9683-faed6cd09cde
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsQHRlc3QuY29tIiwiZXhwIjoxNzExMjg5NjIwLCJ1c2VySWQiOiJjNWE3MTZiOC1lZjZmLTQ2ZjctOTc1Mi01OTQwN2UzMjgzMTAifQ.0SgvJIaL11geyKD6XL_FSTidC7ZBKNz4YMiu7XmzIDo

{
  "id": "58c771a7-4621-47af-9683-faed6cd09cde",
  "userId": "c5a716b8-ef6f-46f7-9752-59407e328310"
}
