PUT http://localhost:8080/films/123-abc-qwerty
Content-Type: "application/json"
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsMUB0ZXN0LmNvbSIsImV4cCI6MTcxMTAyOTczMiwidXNlcklkIjoiNzg5LWFiYy1xd2VydHkifQ.JvcWCQc3WBSeTQr-2KzJQjhUt7P7IOajlKkVVgquIss

{
  "id": "123-abc-qwerty",
  "name": "Crash Landing",
  "type": "Series",
  "description": "Updated the film description. Action and horror everywhere!",
  "categories": [
    "Actions", 
    "Thrillers", 
    "Horrors"
  ],
	"likes": 16,
	"dislikes": 3,
	"comments": [
    "This is a great film. Edit: Actually it is the best film ever.",
    "Could do with more action... actually maybe not."
  ]
}
